# frozen_string_literal: true

# --- Custom inflections for Zeitwerk ---------------------------------------
# These classes use acronym-style names that don't match Zeitwerk's default
# camelize() of their file names, so we teach the inflector about each one.
# (Generated by scanning app/ and lib/ for file-name vs. constant mismatches.)
Rails.autoloaders.each do |autoloader|
  autoloader.inflector.inflect(
    'api_key'            => 'APIKey',
    'api_keys'           => 'APIKeys',
    'api_keys_verifier'  => 'APIKeysVerifier',
    'event_api'          => 'EventAPI',
    'geo_ip'             => 'GeoIP',
    'json_log_formatter' => 'JSONLogFormatter',
    'jwt'                => 'JWT',
    'jwt_authenticator'  => 'JWTAuthenticator',
    'jwt_authentication_middleware' => 'JWTAuthenticationMiddleware',
    'keystore'           => 'KeyStore',
    'mock_sms'           => 'MockSMS',
    'totp_service'       => 'TOTPService',
    'uid_generator'      => 'UIDGenerator',
    'user_with_kyc'      => 'UserWithKYC',
    'cors'               => 'CORS',
    'kyc'                => 'KYC'
  )
end

# --- Custom root namespace for app/api -------------------------------------
# Rails autoloads "app/api" as a flat, namespace-less root by default (like
# every other app/* subdirectory). But Grape endpoints under app/api wrap
# themselves in `module API`, so we need a custom root namespace here.
# See: https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#custom-namespaces
module API; end
Rails.autoloaders.main.push_dir("#{Rails.root}/app/api", namespace: API)
ActiveSupport::Dependencies.autoload_paths.delete("#{Rails.root}/app/api")

